<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Badminton.Contract\Badminton.Contract.csproj" />
    <ProjectReference Include="..\Badminton.DataAccess\Badminton.DataAccess.csproj" />
    <ProjectReference Include="..\Badminton.Model\Badminton.Model.csproj" />
  </ItemGroup>

</Project>
